[project]
name = "kv-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-aiohttp>=1.1.0",
]
